rise_files:
    raw_data_path: '/data/rise_data/'
    raw_patient_file: 'PatientDemographicsData.xlsx'
    raw_lab_file: 'All LaboratoryData_Flat File.csv'
    raw_pharmacy_adamawa_file: 'PharmacyData_Adamawa.xlsx'
    raw_pharmacy_akwa_ibom_file: 'PharmacyData_Akwa Ibom.xlsx'
    raw_pharmacy_cross_river_file: 'PharmacyData_Cross River.xlsx'
    raw_pharmacy_niger_file: 'PharmacyData_Niger.csv'
    raw_pharmacy_file: 'concat_pharmacy_data.csv'
    raw_clinic_file: 'ClinicData.xlsx'
    raw_eac_file: 'EacData.xlsx'
    raw_otz_file: 'OtzData.xlsx'
    raw_drugs_file: 'drugs.csv'
    raw_regimen_file: 'regimen.csv'
    raw_regimen_drug_file: 'regimendrug.csv'
    raw_regimen_line_file: 'regimenline.csv'
    raw_status_history_file: 'statushistory.csv'
    merged_lab_file: 'lab_merged.csv'
    merged_clinic_file: 'clinic_merged.csv'
    merged_pharmacy_file: 'pharmacy_merged.csv'
    
